services:
  php:
    container_name: ${MICROVO_COMPOSE_PROJECT_NAME}_php
    user: 1000:1000
    build:
      context: .docker/php${PHP_VER}-dev
    environment:
      PHP_VER: ${PHP_VER}
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - .:/app:rw
    working_dir: /app
